export type AudioType =
  | 'timeWavePassBy4'
  | 'timeWaveRipple2'
  | 'jumpSpringDown'
  | 'jumpSpringUp'
  | 'thunder'
  | 'yeaah'
  | 'running'
  | 'jumpUp'
  | 'tiger'
  | 'blood'
  | 'scream'
  | 'devoured'
